### PR TITLE
Update requirements

### PR DESCRIPTION
**Pull request by skion**
Modernise requirements used for running tests.

### CODE REVIEW

**Comment by JonathanHuot** [comment]
LGTM. However don't get why the coverage decreased ? Cheers

**Comment by skion** [comment]
Me neither, but it seems flaky [here](https://github.com/oauthlib/oauthlib/pull/517) too...

**Comment by kevin-brown** [comment]
> However don't get why the coverage decreased ?

Looks like there was a build where the Python 2 and Flake8 runs either hit the Python 3-specific lines, or didn't run at all. As far as I can tell, the coverage here matches the upstream coverage.

**Comment by JonathanHuot** [comment]
I checked the latest versions available, here my diff: 

>  -r requirements.txt
> -coverage>=3.7.1
> +coverage==4.5.1
> +mock==2.0.0
>  nose==1.3.7
> -mock>=2.0
> +pbr==3.1.1
> diff --git a/requirements.txt b/requirements.txt
> index e4980c7..2a195b7 100644
> --- a/requirements.txt
> +++ b/requirements.txt
> @@ -1,3 +1,8 @@
> -pyjwt==1.0.0
> -blinker==1.3
> -cryptography>=0.8.1
> +asn1crypto==0.24.0
> +blinker==1.4
> +cffi==1.11.5
> +cryptography==2.2
> +idna==2.6
> +pycparser==2.18
> +PyJWT==1.6.1
> +six==1.11.0

This come from a freeze after a 
`pip install pyjwt[crypto] blinker`

**Pull request merged**
