### PR TITLE
grant_type set to variable

### PR DESCRIPTION
**Pull request by mlboy**

### CODE REVIEW

**Comment by JonathanHuot** [comment]
Is it possible to add the same kwargs processing for other flows ? e.g. `password`, `token` ?
Also, adding unit tests would be warmly appreciated.

**Comment by skion** [comment]
When would someone use a grant type value different from the hard-coded one?

**Comment by JonathanHuot** [comment]
@skion: @mlboy mentionned in https://github.com/oauthlib/oauthlib/issues/610, "Meitu" or internal systems were using custom grant names.

However, after more thinking, I am a bit dubious about the `**kwargs` choice. I'm not keen to change the signature of those methods (even if transparent in `**kwargs`) because it adds complexity where it should not. Also, the rare occurences of such probabilities is so low, that's not worth it.

Instead, to let be everyone happy, specially @mlboy :-), I'm suggesting you should rollback the `**kwargs` and implement it in a different way:
- change the hard-coded values (e.g.`"client_credentials"`) into a class variable (e.g. `BackendApplicationClient.client_credentials = "client_credentials"`) and use this variable instead of the hard-coded values.
- then, if anyone want to use a custom value against a custom-internal provider, it could easily change the class variable without changing the actual implementation, and examples, and unit tests, and so on and so forth...

E.g. 
```python
BackendApplicationClient.client_credentials = "cli_creds"  # was "client_credentials"

# do everything else, as usual
cli = BackendApplicationClient(xxx)
cli.prepare_request_body(..)
```

**Comment by skion** [comment]
That definitely sounds like a better direction, thanks @JonathanHuot!

**Comment by mlboy** [comment]
good idea, i will try it.  waiting me.

**Comment by mlboy** [comment]
Is it better to use “grant_type”  or trait as attribute? 

BackendApplicationClient.grant_type  ?  BackendApplicationClient.client_credentials

just like this?

https://github.com/oauthlib/oauthlib/blob/fabcf865a7f33e5592453189670a82f08dc4384b/oauthlib/oauth2/rfc6749/clients/service_application.py#L32

**Comment by JonathanHuot** [comment]
I think `grant_type` is better for the attribute name. Your example is correct, yes!

**Comment by JonathanHuot** [comment]
Closed in favor of https://github.com/oauthlib/oauthlib/pull/625

**Pull request closed without merging**
