### PR TITLE
added capability to pass kwargs to the grant_type_handler

### PR DESCRIPTION
**Pull request by astrodsg**
specifically to add the ability to turn on/off refresh token generation for a google-like 'offline'/'online' functionality

### CODE REVIEW

**Comment by bjmc** [comment]
:+1:

**Comment by wiliamsouza** [comment]
Need tests and conflicts must be resolved

**Comment by duaneking** [comment]
@astrodsg This build is failing.  If you are still interested in this contribution please update your base and merge so that tests pass.  If not. let us know and we will include it in our cleanup.  Thanks!

**Comment by skion** [comment]
I looked a bit into the history of this and it appears that the functionality of this PR has roughly been implemented by having a setting for the refresh token in the `GrantTypeBase`. I tried rebasing this and it feels a bit like duplication. Anyone against closing?

**Comment by JonathanHuot** [comment]
Agree for closing this.

**Pull request closed without merging**
