### PR TITLE
Remove python 3.5 support; add python 3.8 support

### PR DESCRIPTION
**Pull request by com4**
- Python 3.5 has reached end-of-life.
- Add support for Python 3.8
- Move dist to bionic (xenial is EOL in April)
- Upgrade pip in travis.yml's `before_install`. this should install a wheel
  for pyca/cryptography
- Install rust for pypy builds. It is a requirement for cryptography as no
  pypy wheels exist.

### CODE REVIEW

**Comment by com4** [comment]
It looks like the readthedocs build images support python 3.5, 3.6, 3.7, and 3.8 now. I can bump those versions to 3.8 as a part of this pull request if wanted.

https://github.com/readthedocs/readthedocs-docker-images#read-the-docs---docker-images

**Review by auvipy — CHANGES_REQUESTED** [review]
can you check this failing build of pypy3 https://travis-ci.org/github/oauthlib/oauthlib/jobs/758172309 ?

**Comment by com4** [comment]
Also, this should fix #743 and replace #735

**Review by auvipy — APPROVED** [review]

**Comment by auvipy** [comment]
thanks a lot!

**Pull request merged**
