### PR TITLE
OAuth2 `LegacyApplicationClient.prepare_request_body` now correctly uses the default `scope` provided in constructor

### LINKED ISSUE #725: OAuth2 `LegacyApplicationClient` should honor default scopes in `prepare_request_body`
Hi there,

I found this while using `requests-oauthlib` (https://github.com/requests/requests-oauthlib/issues/406) but it actually belongs here.

Consider this code:

```python
from oauthlib.oauth2 import LegacyApplicationClient
from requests_oauthlib import OAuth2Session

client = LegacyApplicationClient(client_id="my_client_id", scope=['openid', 'profile'])
oauth_session = OAuth2Session(client)

token = oauth_session.fetch_token(token_url='https://<blah>.auth0.com/oauth/ro',
                                                         username=username, password=password,
                                                         include_client_id=True,
                                                         scope=['openid', 'profile']  # this should not be needed
                                  )
```

I currently have to include the `scope` in `fetch_token()` to get a valid token, because the default scopes defined in `LegacyApplicationClient` are not used in `LegacyApplicationClient.prepare_request_body(...)` when `scope=None` is received.

I will submit a PR

### PR DESCRIPTION
**Pull request by smarie**
Fixes #725

### CODE REVIEW

**Comment by smarie** [comment]
Note: `MobileApplicationClient` and `ServiceApplicationClient` as well as `WebApplicationClient` seem to all have the same issue. 

Do you want me to fix them as well ?

**Comment by thedrow** [comment]
Yes please, in separate PRs so we can review them easily.

**Comment by smarie** [comment]
Really ? for one line of fix in each class ? seems a bit overkill :)

**Comment by smarie** [comment]
Thanks for the review. I opened a new issue #728 and PR #729 for the other three classes, and will finally open another one for the base.

**Comment by smarie** [comment]
Thanks @JonathanHuot !

**Pull request merged**
