### PR TITLE
Drop support for Python 2.7

### LINKED ISSUE #698: Drop Python 2.7
Python 2.7's EOL is in January 2020.
We should be prepared to drop the support for it.

This will simplify our codebase and allow us to use newer features.

### PR DESCRIPTION
**Pull request by hugovk**
Fixes #698.

### CODE REVIEW

**Comment by ashleysommer** [comment]
Fixed the failing test on python 2.7

**Comment by thedrow** [comment]
@JonathanHuot Do we want this in 4.0?

**Comment by JonathanHuot** [comment]
I'm a bit worried about the downstream libraries e.g. requests-oauthlib, pythohn-social-auth, many others which are still testing with py2.7

**Comment by thedrow** [comment]
They'll have to drop it soon anyway.

**Pull request merged**
