### PR TITLE
Update create_code_verifier to output the proper length

### PR DESCRIPTION
**Pull request by shawnz**
Previously, `create_code_verifier` would call `secrets.token_urlsafe(nbytes=length)` to produce the code verifier, but this leads to incorrect behaviour because the string returned by `token_urlsafe` doesn't have length `nbytes`. Instead it has length `nbytes * (4/3)` since the output is base64-encoded.

This means that, for example, you could call `create_code_verifier(length=128)` and you would get a result with length 171, which exceeds the 128-character maximum length of the code verifier allowed by the spec. But this wouldn't be caught by the checks in the code, since they only check the input length parameter and not the actual output length.

This PR fixes the issue by using the `generate_token` utility function instead, which does output strings of the exact length you specify. It also adds a test to make sure the length of the outputted string is equal to the specified length.

### CODE REVIEW

**Review by thedrow — APPROVED** [review]

**Review by auvipy — CHANGES_REQUESTED** [review]
we have to make the CI build green

**Comment by shawnz** [comment]
Hi @auvipy, see #878 where I make an attempt to fix the CI errors. I did it in a separate PR since they are not related to this change.

**Comment by auvipy** [comment]
can you please rebase? merged the PR

**Comment by shawnz** [comment]
@auvipy done, ty for looking into this

**Review by auvipy — APPROVED** [review]

**Pull request merged**
